Make `slice` generic.
`slice` should be defined generically because it works for any array,
regardless of element type.

The type parameter context bound `T: Manifest` is necessary to avoid the
following compilation error:

```
[error] Lantern/src/main/scala/lantern/ad_lms_vector.scala:117:76: No Manifest available for Array[T].
[error]   def slice[T](arr: Rep[Array[T]], off: Rep[Int]) = uncheckedPure[Array[T]](arr, "+", off)
```